# Generated by Django 5.2.15 on 2026-07-12 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dormitory_service', '0004_alter_dormitory_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('preferred_room', models.CharField(max_length=40)),
                ('semester', models.CharField(max_length=60)),
                ('req_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('assigned', 'assigned'), ('cancelled', 'cancelled')], max_length=12)),
                ('reviewed_by', models.IntegerField()),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('description', models.TextField()),
                ('requested_dorm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dormitory_service.dormitory')),
            ],
        ),
    ]
