# Generated by Django 5.2.15 on 2026-07-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodation',
            options={'ordering': ['-req_date']},
        ),
        migrations.AlterModelTable(
            name='accommodation',
            table='accommodation',
        ),
    ]
