# Generated by Django 5.2.15 on 2026-07-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation_service', '0002_alter_accommodation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='description',
            field=models.TextField(default='desc'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='reviewed_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('assigned', 'assigned'), ('cancelled', 'cancelled')], default='pending', max_length=12),
        ),
    ]
