# Generated by Django 5.2.15 on 2026-07-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation_service', '0003_alter_accommodation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='review_note',
            field=models.TextField(default='no-desc'),
        ),
    ]
