# Generated by Django 5.2.15 on 2026-07-17 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation_service', '0004_accommodation_review_note'),
        ('dormitory_service', '0006_alter_bedassign_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='requested_dorm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory_service.dormitory'),
        ),
    ]
