# Generated by Django 5.2.14 on 2026-06-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='currentOccupancy',
            field=models.IntegerField(default=0),
        ),
    ]
