# Generated by Django 5.2.14 on 2026-06-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitories', '0002_room_currentoccupancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='occupant_id',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='occupant_name',
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('id', 'roomNumber')},
        ),
    ]
