# Generated by Django 5.2.14 on 2026-06-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitories', '0003_remove_bed_occupant_id_remove_bed_occupant_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('id', 'bedNumber')},
        ),
    ]
