# Generated by Django 5.2.15 on 2026-07-15 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dormitory_service', '0006_alter_bedassign_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_id', models.IntegerField()),
                ('title', models.CharField(default='title', max_length=40)),
                ('description', models.TextField(default='desc')),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('urgent', 'urgent')], max_length=7)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('progress', 'progress'), ('in_progress', 'in_progress'), ('resolved', 'resolved'), ('rejected', 'rejected'), ('cancelled', 'cancelled')], max_length=12)),
                ('assigned_to', models.IntegerField(null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory_service.bed')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory_service.room')),
            ],
            options={
                'db_table': 'maintenance',
            },
        ),
    ]
