# Generated by Django 5.2.15 on 2026-07-15 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory_service', '0006_alter_bedassign_notes'),
        ('maintenance_service', '0002_alter_maintenance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='dorm',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dormitory_service.dormitory'),
            preserve_default=False,
        ),
    ]
