# Generated by Django 5.2.14 on 2026-07-08 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dorm_type', models.CharField(choices=[('b', 'Boys'), ('g', 'Girls')], default='b', max_length=1)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=1)),
                ('address', models.TextField(blank=True, null=True)),
                ('totalRoom', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('currentOccupancy', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dormitory',
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNumber', models.IntegerField()),
                ('floorNumber', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'AVAILABLE'), ('full', 'FULL'), ('maintenance', 'MAINTENANCE'), ('closed', 'CLOSED')], default='available', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('currentOccupancy', models.IntegerField(default=0)),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='dormitory_service.dormitory')),
            ],
            options={
                'db_table': 'room',
                'ordering': ['roomNumber'],
                'unique_together': {('id', 'roomNumber')},
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedNumber', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('available', 'AVAILABLE'), ('occupied', 'OCCUPIED'), ('reserved', 'RESERVED'), ('maintenance', 'MAINTENANCE')], default='available', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='dormitory_service.room')),
            ],
            options={
                'db_table': 'bed',
                'ordering': ['createdAt'],
                'unique_together': {('id', 'bedNumber')},
            },
        ),
    ]
