# Generated by Django 5.2.14 on 2026-07-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='bingo',
            field=models.IntegerField(default=0),
        ),
    ]
