# Generated by Django 5.2.14 on 2026-07-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory_service', '0002_dormitory_bingo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dormitory',
            name='bingo',
        ),
    ]
