# Generated by Django 5.2.15 on 2026-07-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory_service', '0003_remove_dormitory_bingo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('s', 'shared')], default='m', max_length=1),
        ),
    ]
