# Generated by Django 5.2.15 on 2026-07-13 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation_service', '0004_accommodation_review_note'),
        ('dormitory_service', '0004_alter_dormitory_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('assigned_by', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('ended', 'ended'), ('cancelled', 'cancelled')], default='inactive', max_length=12)),
                ('notes', models.TextField()),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory_service.bed')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accomodation_service.accommodation')),
            ],
            options={
                'db_table': 'BedAssign',
            },
        ),
    ]
