# Generated by Django 5.2.15 on 2026-07-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory_service', '0005_bedassign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedassign',
            name='notes',
            field=models.TextField(default='desc'),
        ),
    ]
