# Generated by Django 5.2.14 on 2026-07-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory_service', '0006_alter_bedassign_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedassign',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bedassign',
            name='start_date',
            field=models.DateField(),
        ),
    ]
