# Generated by Django 5.2.14 on 2026-07-04 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalId', models.BigIntegerField()),
                ('studentId', models.BigIntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=14)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=7)),
                ('profileImage', models.CharField(max_length=256)),
                ('faceImage', models.CharField(max_length=256)),
                ('isVerified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
