# Generated by Django 5.2.14 on 2026-07-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_service', '0002_permission_role_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='faceImage',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profileImage',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
