# Generated by Django 5.2.14 on 2026-07-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_service', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bingo',
            field=models.IntegerField(default=1),
        ),
    ]
