# Generated by Django 5.2.14 on 2026-07-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_service', '0005_userprofile_bingo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bingo',
        ),
    ]
