# Generated by Django 5.2.15 on 2026-07-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_service', '0006_remove_userprofile_bingo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('student', 'student'), ('dorm-staff', 'dorm-staff'), ('system-admin', 'system-admin'), ('support-staff', 'support-staff')], max_length=30),
        ),
    ]
