# Generated by Django 5.2.15 on 2026-07-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_service', '0007_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('student', 'student'), ('dorm-admin', 'dorm-admin'), ('system-admin', 'system-admin'), ('support-staff', 'support-staff')], max_length=30),
        ),
    ]
